-- -----------------------------------------------------------------------------
-- FULL CLEANUP SCRIPT: Healthcare Intelligence Demo
-- -----------------------------------------------------------------------------

USE ROLE ACCOUNTADMIN;
DROP CORTEX SEARCH SERVICE IF EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS.CLAIM_PDF_CHUNKS_SEARCH_SERVICE;
DROP TABLE IF EXISTS HEALTHCARE_DEMO_DB.PUBLIC.CLAIM_PDF_CHUNKS;
DROP TABLE IF EXISTS HEALTHCARE_DEMO_DB.PUBLIC.PARSED_PDFS;
DROP TABLE IF EXISTS HEALTHCARE_DEMO_DB.PUBLIC.PATIENTS;
DROP TABLE IF EXISTS HEALTHCARE_DEMO_DB.PUBLIC.PROVIDERS;
DROP TABLE IF EXISTS HEALTHCARE_DEMO_DB.PUBLIC.CLAIMS;
DROP TABLE IF EXISTS HEALTHCARE_DEMO_DB.PUBLIC.APPOINTMENTS;
DROP TABLE IF EXISTS HEALTHCARE_DEMO_DB.PUBLIC.PRESCRIPTIONS;
DROP STAGE IF EXISTS HEALTHCARE_DEMO_DB.PUBLIC.HEALTHCARE_DEMO_STAGE;
DROP DATABASE IF EXISTS HEALTHCARE_DEMO_DB;
DROP DATABASE IF EXISTS SNOWFLAKE_INTELLIGENCE;
DROP WAREHOUSE IF EXISTS SNOWFLAKE_INTELLIGENCE_WH;
DROP SCHEMA IF EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS;
DROP ROLE IF EXISTS SNOWFLAKE_INTELLIGENCE_ADMIN_RL;
-- if created semantic view
DROP SEMANTIC VIEW IF EXISTS healthcare_demo_semantic_vw;

-- NOTE: Drop Semantic Models & Cortex Agents manually
-- These currently require manual removal via Snowsight UI:
--   1. Go to Snowsight > Semantic Models > Delete 'healthcare_data.yaml'
--   2. Go to Snowsight > Agents > Delete any Agents you created

